stages:
  - lint
  - build
  - test
  - deploy

build:
  image: archlinux:latest
  stage: build
  needs: []
  before_script:
  - pacman -Sy icu cmake gcc make patch --noconfirm
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

windows-build:
  stage: build
  needs: []
  variables:
    ICU_ROOT: "ICU"
  tags:
    - windows
  before_script:
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - choco install cmake.install --installargs '"ADD_CMAKE_TO_PATH=System"' -y
    - choco install 7zip -y
    - refreshenv
  script:
    - mkdir build
    - cd build
    - iwr https://github.com/unicode-org/icu/releases/download/release-69-1/icu4c-69_1-Win64-MSVC2019.zip -OutFile icu4c-69_1-Win64-MSVC2019.zip
    - 7z x -oICU icu4c-69_1-Win64-MSVC2019.zip
    - cmake -DICU_LIBRARY="ICU/bin64/icuuc69.dll" -DICU_INCLUDE_DIR="ICU/include" ..
    - cmake --build .

test:
  image: archlinux:latest
  stage: test
  needs: []
  before_script:
  - pacman -Sy icu gtest boost cmake gcc make lcov patch --noconfirm
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make test
    - gcov tests/CMakeFiles/run_tests.dir/__/**/*.gcno
    - lcov --capture --directory tests/CMakeFiles/run_test.dir/__/ --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' -o coverage_filtered.info
    - lcov --remove coverage_filtered.info `pwd`'/lexy/*' -o coverage_filtered2.info
    - lcov --list coverage_filtered2.info
  allow_failure: true

clang-format:
  image: archlinux:latest
  stage: lint
  needs: []
  before_script:
  - pacman -Sy clang --noconfirm
  script:
    - shopt -s globstar
    - clang-format -n -Werror include/**/*.hpp src/*.cpp tests/*.cpp

pages:
  image: alpine
  stage: deploy
  script:
  - apk update && apk add doxygen
  - doxygen Doxyfile
  - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
