stages:
  - lint
  - build
  - test

clang-format:
  image: archlinux:latest
  stage: lint
  needs: []
  before_script:
  - pacman -Sy clang --noconfirm
  script:
    - shopt -s globstar
    - clang-format -n -Werror include/**/*.hpp src/*.cpp tests/*.cpp

pages:
  image: alpine
  script:
  - apk update && apk add doxygen
  - doxygen doxygen/Doxyfile
  - mv doxygen/doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
