stages:
  - lint
  - build
  - test
  - deploy

build:
  image: archlinux:latest
  stage: build
  needs: []
  before_script:
  - pacman -Sy icu cmake gcc make --noconfirm
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

test:
  image: archlinux:latest
  stage: test
  needs: []
  before_script:
  - pacman -Sy icu gtest boost cmake gcc make --noconfirm
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make test
  allow_failure: true

clang-format:
  image: archlinux:latest
  stage: lint
  needs: []
  before_script:
  - pacman -Sy clang --noconfirm
  script:
    - shopt -s globstar
    - clang-format -n -Werror include/**/*.hpp src/*.cpp tests/*.cpp

pages:
  image: alpine
  stage: deploy
  script:
  - apk update && apk add doxygen
  - doxygen Doxyfile
  - mv doxygen/doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
