repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: \.ftl$
      - id: end-of-file-fixer
        exclude: \.ftl$
      - id: check-yaml
      - id: check-added-large-files
      - id: sort-simple-yaml
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.4
    hooks:
      - id: clang-format
