repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: \.ftl$
      - id: end-of-file-fixer
        exclude: \.ftl$
      - id: check-yaml
      - id: check-added-large-files
      - id: sort-simple-yaml
  - repo: https://github.com/doublify/pre-commit-clang-format
    rev: 62302476d0da01515660132d76902359bed0f782
    hooks:
      - id: clang-format
